### ISSUE TITLE
How to run without GOGS

### ISSUE THREAD

**Issue by anhkind** [hypriot/rpi-drone#1]
How can I run drone without `DRONE_GOGS_URL` and `DRONE_GOGS_SECRET` env settings? 
Thanks.

**Comment by firecyberice** [comment]
What are you trying to achieve?
You need to use a auth provider like GitLab GitHub Bitbucket or GOGS.
Please have a look at http://readme.drone.io/setup/config/settings/.
For getting it to work with github or bitbucket your drone has to be publicly available for the callback url.

**Comment by anhkind** [comment]
So let's say I want to run it with my GitHub credentials then what should be the command that I need to run?

**Comment by firecyberice** [comment]
Please read the drone.io docs how to use github.
Additionally I already said that you need to make the drone available to the internet so that github can access your drone website.
