### ISSUE TITLE
Current source version not in sync with docker hub published image

### ISSUE THREAD

**Issue by surfacelevel** [hypriot/rpi-drone#7]
The source code of this repository has the base image of `resin/rpi-raspbian:jessie` but the image that's published in docker hub is on `wheezy` as can be seen below. In order to implement some simple strategies described here https://jpetazzo.github.io/2015/09/03/do-not-use-docker-in-docker-for-ci/ both the host image and the container image must match.

Unfortunately this image is built with resources from a private S3 bucket so it's not possible to rebuild locally without building an armv7 version of drone. Please update the image in docker hub.

The host is running the latest Hypriot jessie image:

```
HypriotOS: root@guac in ~
$ cat /etc/*-release
PRETTY_NAME="Raspbian GNU/Linux 8 (jessie)"
NAME="Raspbian GNU/Linux"
VERSION_ID="8"
VERSION="8 (jessie)"
ID=raspbian
ID_LIKE=debian
HOME_URL="http://www.raspbian.org/"
SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"
```

The rpi-drone container is running wheezy: 

```
HypriotOS: root@guac in ~
$ docker run -it --rm --entrypoint=/bin/bash hypriot/rpi-drone 
root@d45277d2df1e:/gopath/src/github.com/drone/drone# cat /etc/*-release
PRETTY_NAME="Raspbian GNU/Linux 7 (wheezy)"
NAME="Raspbian GNU/Linux"
VERSION_ID="7"
VERSION="7 (wheezy)"
ID=raspbian
ID_LIKE=debian
ANSI_COLOR="1;31"
HOME_URL="http://www.raspbian.org/"
SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"
```

**Comment by firecyberice** [comment]
This repo is deprecated it builds an old drone 0.3.xx version.

**Comment by firecyberice** [comment]
Have a look at https://hub.docker.com/u/armdrone/ for a newer (0.4.x) version of drone.
I am working on publishing the build source.

**Comment by surfacelevel** [comment]
Thank you. I will check out those images
